public class Images {
  public PImage defenderShipAsset;
  public PImage defenderShipAssetPlayerTwo;
  public PImage shieldAsset;
  public PImage backgroundAsset;
  public PImage playButtonAsset;
  public PImage playButtonAssetHighlighted;
  public PImage quitButtonAsset;
  public PImage quitButtonAssetHighlighted;
  public PImage hostButtonAsset;
  public PImage hostButtonAssetHighlighted;
  public PImage joinButtonAsset;
  public PImage joinButtonAssetHighlighted;
  public PImage backButtonAsset;
  public PImage backButtonAssetHighlighted;
  public PImage bannerAsset;
  public PImage multiplayerButtonAsset;
  public PImage multiplayerButtonAssetHighlighted;
  public PImage alienBulletAsset;
  public PImage explosionAsset;
  public PImage alienShipAsset;
  public PImage bulletAsset;
  public PImage statsBoard;

  public Images() {
    defenderShipAsset = loadImage("assets/defenderShipAsset.png");
    defenderShipAssetPlayerTwo = loadImage("assets/defenderShipAssetPlayerTwo.png");
    shieldAsset = loadImage("assets/shieldAsset.png");
    backgroundAsset = loadImage("assets/background.png");
    playButtonAsset = loadImage("assets/playButtonAsset.png");
    playButtonAssetHighlighted = loadImage("assets/playButtonAssetHighlighted.png");
    quitButtonAsset = loadImage("assets/quitButtonAsset.png");
    quitButtonAssetHighlighted = loadImage("assets/quitButtonAssetHighlighted.png");
    hostButtonAsset = loadImage("assets/hostButtonAsset.png");
    hostButtonAssetHighlighted = loadImage("assets/hostButtonAssetHighlighted.png");
    joinButtonAsset = loadImage("assets/joinButtonAsset.png");
    joinButtonAssetHighlighted = loadImage("assets/joinButtonAssetHighlighted.png");
    backButtonAsset = loadImage("assets/backButtonAsset.png");
    backButtonAssetHighlighted = loadImage("assets/backButtonAssetHighlighted.png");
    bannerAsset = loadImage("assets/bannerAsset.png");
    multiplayerButtonAsset = loadImage("assets/multiplayerButtonAsset.png");
    multiplayerButtonAssetHighlighted = loadImage("assets/multiplayerButtonAssetHighlighted.png");
    alienBulletAsset = loadImage("assets/alienBulletAsset.png");
    alienShipAsset = loadImage("assets/alienShip.png");
    bulletAsset = loadImage("assets/bulletAsset.png");
    explosionAsset = loadImage("assets/explosion.png");
    statsBoard = loadImage("assets/statsBoard.png");
  }
}
